version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: db_shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    hostname: db

  server:
    build: server
    image: server-image
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  gateway:
    build: gateway
    image: gateway_image
    container_name: gateway_container
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - GATEWAY_PORT=8080